version: '3.8'

services:
  python:
    build:
      context: .
    container_name: fastapiapp
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    networks:
      - my_network
    command: ["uvicorn", "main:app","--host","0.0.0.0", "--reload"]  # Comando para iniciar o servidor FastAPI

  mysql:
    image: mysql:latest
    container_name: mysqlapp
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: "5912"
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my_network

volumes:
  mysql_data:

networks:
  my_network:
    driver: bridge
